const monsters = [
  {
    id: 1,
    name: "슬라임",
    difficulty: "easy",
    image: "/images/slime.png",
    description: "초보자를 위한 몬스터",
  },
  {
    id: 2,
    name: "고블린",
    difficulty: "normal",
    image: "/images/goblin.png",
    description: "빠른 타이핑이 필요함",
  },
  {
    id: 3,
    name: "드래곤",
    difficulty: "hard",
    image: "/images/dragon.png",
    description: "보스 몬스터",
  },
  {
    id: 4,
    name: "오크",
    difficulty: "normal",
    image: "/images/orc.png",
    description: "강력한 몽둥이를 휘두른다",
  },
  {
    id: 5,
    name: "스켈레톤",
    difficulty: "easy",
    image: "/images/skeleton.png",
    description: "느리지만 끈질긴 몬스터",
  },
  {
    id: 6,
    name: "좀비",
    difficulty: "easy",
    image: "/images/zombie.png",
    description: "천천히 접근하는 언데드",
  },
  {
    id: 7,
    name: "미믹",
    difficulty: "hard",
    image: "/images/mimic.png",
    description: "보물상자로 위장한다",
  },
  {
    id: 8,
    name: "하피",
    difficulty: "normal",
    image: "/images/harpy.png",
    description: "빠른 속도로 공격한다",
  },
  {
    id: 9,
    name: "와이번",
    difficulty: "hard",
    image: "/images/wyvern.png",
    description: "독을 사용하는 비룡",
  },
  {
    id: 10,
    name: "골렘",
    difficulty: "hard",
    image: "/images/golem.png",
    description: "높은 방어력을 가진 몬스터",
  },

  {
    id: 11,
    name: "파이어 슬라임",
    difficulty: "normal",
    image: "/images/fire_slime.png",
    description: "불속성을 가진 슬라임",
  },
  {
    id: 12,
    name: "아이스 골렘",
    difficulty: "hard",
    image: "/images/ice_golem.png",
    description: "차가운 냉기를 뿜는다",
  },
  {
    id: 13,
    name: "박쥐",
    difficulty: "easy",
    image: "/images/bat.png",
    description: "동굴에 서식한다",
  },
  {
    id: 14,
    name: "리자드맨",
    difficulty: "normal",
    image: "/images/lizardman.png",
    description: "창을 사용하는 전사",
  },
  {
    id: 15,
    name: "암흑 기사",
    difficulty: "hard",
    image: "/images/dark_knight.png",
    description: "강력한 검술을 사용한다",
  },
  {
    id: 16,
    name: "팬텀",
    difficulty: "normal",
    image: "/images/phantom.png",
    description: "그림자 속에서 나타난다",
  },
  {
    id: 17,
    name: "늑대",
    difficulty: "easy",
    image: "/images/wolf.png",
    description: "빠르게 달려든다",
  },
  {
    id: 18,
    name: "마법사 고블린",
    difficulty: "normal",
    image: "/images/goblin_mage.png",
    description: "화염 마법을 사용한다",
  },
  {
    id: 19,
    name: "데몬",
    difficulty: "hard",
    image: "/images/demon.png",
    description: "지옥에서 소환된 악마",
  },
  {
    id: 20,
    name: "엔트",
    difficulty: "normal",
    image: "/images/ent.png",
    description: "거대한 나무 몬스터",
  },

  {
    id: 21,
    name: "크로우",
    difficulty: "easy",
    image: "/images/crow.png",
    description: "빠르게 날아다닌다",
  },
  {
    id: 22,
    name: "스톤 골렘",
    difficulty: "hard",
    image: "/images/stone_golem.png",
    description: "바위로 이루어진 거인",
  },
  {
    id: 23,
    name: "독거미",
    difficulty: "normal",
    image: "/images/spider.png",
    description: "독 공격을 사용한다",
  },
  {
    id: 24,
    name: "트롤",
    difficulty: "hard",
    image: "/images/troll.png",
    description: "체력 회복 능력이 뛰어나다",
  },
  {
    id: 25,
    name: "임프",
    difficulty: "easy",
    image: "/images/imp.png",
    description: "장난을 좋아하는 악마",
  },

  // 이하 동일 패턴 반복

  {
    id: 26,
    name: "샌드웜",
    difficulty: "hard",
    image: "/images/sandworm.png",
    description: "사막 지하를 이동한다",
  },
  {
    id: 27,
    name: "유령",
    difficulty: "normal",
    image: "/images/ghost.png",
    description: "물리 공격이 통하지 않는다",
  },
  {
    id: 28,
    name: "머드 슬라임",
    difficulty: "easy",
    image: "/images/mud_slime.png",
    description: "진흙으로 이루어진 슬라임",
  },
  {
    id: 29,
    name: "사이클롭스",
    difficulty: "hard",
    image: "/images/cyclops.png",
    description: "거대한 외눈 몬스터",
  },
  {
    id: 30,
    name: "케르베로스",
    difficulty: "hard",
    image: "/images/cerberus.png",
    description: "세 개의 머리를 가진 마수",
  },

  {
    id: 31,
    name: "라바 골렘",
    difficulty: "hard",
    image: "/images/lava_golem.png",
    description: "용암으로 이루어진 골렘",
  },
  {
    id: 32,
    name: "서큐버스",
    difficulty: "normal",
    image: "/images/succubus.png",
    description: "환영 마법을 사용한다",
  },
  {
    id: 33,
    name: "미노타우르스",
    difficulty: "hard",
    image: "/images/minotaur.png",
    description: "거대한 도끼를 휘두른다",
  },
  {
    id: 34,
    name: "픽시",
    difficulty: "easy",
    image: "/images/pixie.png",
    description: "숲속에 사는 요정",
  },
  {
    id: 35,
    name: "네크로맨서",
    difficulty: "hard",
    image: "/images/necromancer.png",
    description: "언데드를 소환한다",
  },

  {
    id: 36,
    name: "크라켄",
    difficulty: "hard",
    image: "/images/kraken.png",
    description: "바다 깊은 곳의 괴물",
  },
  {
    id: 37,
    name: "엘프 궁수",
    difficulty: "normal",
    image: "/images/elf_archer.png",
    description: "정확한 활 공격을 한다",
  },
  {
    id: 38,
    name: "듀라한",
    difficulty: "hard",
    image: "/images/dullahan.png",
    description: "머리 없는 기사",
  },
  {
    id: 39,
    name: "펭귄 슬라임",
    difficulty: "easy",
    image: "/images/penguin_slime.png",
    description: "빙하 지역에 서식한다",
  },
  {
    id: 40,
    name: "불사조",
    difficulty: "hard",
    image: "/images/phoenix.png",
    description: "죽어도 다시 부활한다",
  },
];

// 41 ~ 100도 같은 패턴으로 추가 가능

export default monsters;
